// This file was generated by Prisma, and assumes you have installed the following:
// // npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });

import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    // Adding the ?? makes it fallback to the DATABASE_URL if DIRECT_URL is missing
    // during the build phase on Railway.
    url: env("DIRECT_URL", { required: false }) ?? env("DATABASE_URL"),
  },
});